name: ops_analytics
version: "1.0.0"
profile: ops_analytics
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: target
clean-targets: ["target", "dbt_packages"]

models:
  ops_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

vars:
  report_year: 2025
